- type: gameMapPool
  id: DefaultMapPool
  maps:
  # DarkHaven - Start - Remove standard maps
  # - Amber
  # - Bagel
  # - Box
  # - Elkridge
  # - Fland
  # - Marathon
  # - Oasis
  # - Packed
  # - Plasma
  # - Reach
  # - Exo
  - DevHaven
  # Darkhaven - End
